### PR TITLE
Update join-code input type (text -> number)

### PR DESCRIPTION
**Pull request by darkyben**
Force smartphone keyboard (iOS & Android) to display a number-only keyboard layout.

### CODE REVIEW

**Review by kcgidw — APPROVED** [review]

**Comment by kcgidw** [comment]
Thanks, I completely forgot about this.
This breaks the styling, but that should be easy to fix. My main concern at this point is what to do with the spinner that browsers add to number inputs. As far as I understand, any solution to this is pretty nonstandard.

**Comment by darkyben** [comment]
would something like this work ?

input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
    -webkit-appearance: none;
    margin: 0;
}

?

**Comment by kcgidw** [comment]
Yes, for Chrome. I'm still trying to figure out Firefox's fix. I've found some stuff on stackoverflow but it's not doing what I'd like it to do.

On another note, I'm strongly considering changing the input type to "tel" instead of "number". That way, there's no spinner. Also, the mobile "tel" keyboard puts much greater emphasis on the number digits, while some mobile "number" keyboards are still pretty cluttered.

**Comment by darkyben** [comment]
Just tried on android & iOS : type "tel" is a great choice ! :+1:

**Pull request merged**
